### ISSUE TITLE
Whitelisting players to directly join the backend to diagnose issues.

### ISSUE THREAD

**Issue by ytendx** [NeoProtect/NeoPlugin#3]
**Is your feature request related to a problem? Please describe.**
Yes, testing ping issues

**Describe the solution you'd like**
Having a command to disable adding the proxy protocol handler to a players pipeline to allow him to join directly.
This might be done via a command and via whitelisting a certain ip.

**Comment by ytendx** [comment]
whitelistDirectConnect

**Comment by EinfacheSache** [comment]
> whitelistDirectConnect

Hey ytendx,
is now added and will be availeble in the next update ;)
